apiVersion: 1
datasources:
  - name: Wazuh Indexer
    type: grafana-opensearch-datasource
    access: proxy
    url: https://wazuh.indexer:9200
    basicAuth: true
    basicAuthUser: admin
    jsonData:
      timeField: "@timestamp"
      logLevelField: rule.level
      database: "wazuh-alerts-*"
      tlsSkipVerify: true
      version: "2.0.0"
      flavor: opensearch
    secureJsonData:
      basicAuthPassword: SecretPassword
    editable: true
